
ARTICLES_COLLECTION = "articles"
ARTICLE_EMBEDDINGS_COLLECTION = "article_embeddings"
ARTICLES_VECTORS_COLLECTION = "articles_vectors"
TOPIC_ASSIGNMENTS_COLLECTION = "topics"
TOPIC_EMBEDDINGS_COLLECTION = "topic_embeddings"
TOPICS_VECTORS_COLLECTION = "topics_vectors"
